# Generated by Django 5.1.1 on 2024-12-07 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_max', models.IntegerField()),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('potion', 'Potion'), ('plante', 'Plante'), ('arme', 'Arme'), ('clé', 'Clé'), ('armure', 'Pièce d’armure')], max_length=20)),
                ('space', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_in_bag', to='App.bag')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('chance', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('life_point', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=150, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_mail', models.EmailField(max_length=254, unique=True)),
                ('user_date_new', models.DateTimeField(auto_now_add=True)),
                ('user_date_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.item')),
                ('class_list', models.JSONField()),
                ('place', models.CharField(max_length=100)),
            ],
            bases=('App.item',),
        ),
        migrations.AddField(
            model_name='bag',
            name='items',
            field=models.ManyToManyField(related_name='bags_containing_item', to='App.item'),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='stat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat'),
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=100)),
                ('lvl', models.IntegerField(default=1)),
                ('life', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.classe')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.race')),
                ('stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('avatar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.avatar')),
                ('xp', models.IntegerField(default=1)),
                ('profession', models.CharField(max_length=100)),
                ('bag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_bag', to='App.bag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='App.user')),
                ('equipment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_equipment', to='App.equipment')),
            ],
            bases=('App.avatar',),
        ),
        migrations.AddField(
            model_name='bag',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_bag', to='App.hero'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_equipment', to='App.hero'),
        ),
    ]
