# Generated by Django 5.1.1 on 2024-12-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('potion', 'Potion'), ('plante', 'Plante'), ('arme', 'Arme'), ('clé', 'Clé'), ('armure', 'Pièce d’armure')], max_length=20)),
                ('space', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('chance', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('life_point', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=150, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_mail', models.EmailField(max_length=254, unique=True)),
                ('user_date_new', models.DateTimeField(auto_now_add=True)),
                ('user_date_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_max', models.IntegerField()),
                ('items', models.ManyToManyField(related_name='bags_containing_item', to='App.item')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('humain', 'Humain'), ('elfe', 'Elfe'), ('nain', 'Nain'), ('orc', 'Orc'), ('gobelin', 'Gobelin')], max_length=100)),
                ('stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='stat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('bottes', 'Bottes'), ('jambieres', 'Jambières'), ('plastron', 'Plastron'), ('casque', 'Casque'), ('gants', 'Gants'), ('arme', 'Arme'), ('bouclier', 'Bouclier')], max_length=50)),
                ('space', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('guerrier', 'Guerrier'), ('mage', 'Mage'), ('archer', 'Archer'), ('voleur', 'Voleur'), ('pretre', 'Prêtre')], max_length=100)),
                ('stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=100)),
                ('lvl', models.IntegerField(default=1)),
                ('life', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.classe')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.race')),
                ('stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.stat')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('avatar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='App.avatar')),
                ('hero_id', models.AutoField(primary_key=True, serialize=False)),
                ('xp', models.IntegerField(default=1)),
                ('profession', models.CharField(max_length=100)),
                ('bag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_bag', to='App.bag')),
                ('equipment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_equipment', to='App.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='App.user')),
            ],
            bases=('App.avatar',),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_equipment', to='App.hero'),
        ),
        migrations.AddField(
            model_name='bag',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_bag', to='App.hero'),
        ),
    ]
