# Generated by Django 5.1.1 on 2024-12-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bag',
        ),
    ]
