# Generated by Django 5.1.1 on 2024-12-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_item_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='avatar_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='App.avatar'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
